VOD.Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VOD.Admin.ViewModel;
using VOD.Common.DTOModel;
using VOD.Common.Entities;
using VOD.Database.Service;
using X.PagedList;
using VOD.Common.Extensions;

namespace VOD.Admin.Controllers
{
    public class BookController : Controller
    {

        private readonly string _userId;

        private readonly IMapper _mapper;

        private readonly VOD.Common.Service.IUIReadService _dbRead;
        private readonly VOD.Common.Service.IUIWriteService _dbWrite;


        public BookController(IHttpContextAccessor httpContextAccessor,
            UserManager<VODUser> userManager, IMapper mapper, VOD.Common.Service.IUIReadService dbRead, VOD.Common.Service.IUIWriteService dbWrite)
        {
            var user = httpContextAccessor.HttpContext.User;
            _userId = userManager.GetUserId(user);
            _mapper = mapper;
            _dbRead = dbRead;
            _dbWrite = dbWrite;
        }
        [HttpGet]
        public async Task<IActionResult> BookList(int? id, int? authId)
        {

            Dictionary<string, object> _properties = new Dictionary<string, object>();
            _properties.Add("ID", 2);


            var booksDto = await _dbRead.GetAsync<Book, BookDTO>(true);
            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            SelectList selectList = new SelectList(authorDto, "ID", "Name");
            //var AuthorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            var pageSize = 20;
            var pageNum = (id ?? 1);

            BookViewModel vm = new BookViewModel();
            vm.Books = await booksDto.ToPagedListAsync(pageNum, pageSize);
            vm.AuthorsList = selectList;
            if (authId.HasValue && authId.Value > 0)
            {
                string[] dataSource =
                    { "1", "orange", "peach", "melon", "grape" };
                var result = booksDto.AsQueryable().Where(LinqExpressionExtension.GetExpressionTreeWhere<BookDTO>(15));

                if(result.Any())
                {
                    string s = "";
                }

                vm.Author_ID = authId.Value;
                var ret = booksDto.Where(item => item.ID.Equals(15));

                vm.Books = await booksDto.Where(x => x.Author_ID.Equals(authId)).ToPagedListAsync(pageNum, pageSize);
                vm.AuthorsList = new SelectList(authorDto, "ID", "Name", authId);
            }
            return View(vm);

        }
        [HttpPost]
        public async Task<IActionResult> BookList([Bind("Author_ID")]BookDTO book, int? id)
        {

            var booksDto = await _dbRead.GetAsync<Book, BookDTO>(true);
            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            SelectList selectList = new SelectList(authorDto, "ID", "Name");
            //var AuthorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            var pageSize = 20;
            var pageNum = (id ?? 1);

            BookViewModel vm = new BookViewModel();
            vm.Author_ID = book.Author_ID;
            vm.Books = await booksDto.Where(x => x.Author_ID.Equals(book.Author_ID)).ToPagedListAsync(pageNum, pageSize);
            vm.AuthorsList = selectList;
            return View(vm);

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            SelectList selectList = new SelectList(authorDto, "ID", "Name");

            var bookVieModel = new BookViewModel()
            {
                AuthorsList = selectList
            };

            return View(bookVieModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID, Title, Price, Publisher, Sample, ReleaseDate, Author_ID")]BookDTO book)
        {
            if (ModelState.IsValid)
            {
                book.CreateDate = DateTime.Now;
                book.UpdateDate = DateTime.Now;
                await _dbWrite.CreateAsync<BookDTO, Book>(book);
                return RedirectToAction(nameof(BookList));
            }
            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            SelectList selectList = new SelectList(authorDto, "ID", "Name");
            var bookVieModel = new BookViewModel()
            {
                Book = book,
                AuthorsList = selectList
            };
            return View(bookVieModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //var book = await _dbRead.GetBook(id);
            //if (book == null)
            //{
            //    return NotFound();
            //}
            int ID = id.Value;
            var bookDto = await _dbRead.GetSingleAsync<Book, BookDTO>(x => x.ID.Equals(ID), true);
            if (bookDto == null)
            {
                return NotFound();
            }

            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
            SelectList selectList = new SelectList(authorDto, "ID", "Name", authorDto.Single(x => x.ID.Equals(bookDto.Author_ID)));
            var bookVieModel = new BookViewModel()
            {
                Book = bookDto,
                AuthorsList = selectList
            };
            return View(bookVieModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, Title, Price, Publisher, Sample, ReleaseDate, Author_ID,RowVersion")]BookDTO book)
        {
            if (book.ID != id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (book.CreateDate == null) { book.CreateDate = DateTime.Now; }
                book.UpdateDate = DateTime.Now;

                await _dbWrite.UpdateAsync<BookDTO, Book>(book);
                return RedirectToAction(nameof(BookList));
            }
            var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);

            SelectList selectList = new SelectList(authorDto, "ID", "Name", authorDto.Single(x => x.ID.Equals(book.Author_ID)));
            var bookVieModel = new BookViewModel()
            {
                Book = book,
                AuthorsList = selectList
            };
            return View(bookVieModel);

        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                int ID = id.Value;
                var bookDto = await _dbRead.GetSingleAsync<Book, BookDTO>(x => x.ID.Equals(ID), true);
                if (bookDto == null)
                {
                    return NotFound();
                }

                var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
                SelectList selectList = new SelectList(authorDto, "ID", "Name", authorDto.Single(x => x.ID.Equals(bookDto.Author_ID)));
                var bookVieModel = new BookViewModel()
                {
                    Book = bookDto,
                    AuthorsList = selectList
                };
                return View(bookVieModel);
            }
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            else
            {
                try
                {
                    int ID = id.Value;
                    var bookDto = await _dbRead.GetSingleAsync<Book, BookDTO>(x => x.ID.Equals(ID), true);
                    if (bookDto == null)
                    {
                        return NotFound();
                    }

                    await _dbWrite.DeleteAsync<Book>(x => x.ID.Equals(ID));
                    return RedirectToAction(nameof(BookList));

                }
                catch (Exception)
                {
                    //await unit.RollbackAsync();
                    throw;
                }

            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                int ID = id.Value;
                var bookDto = await _dbRead.GetSingleAsync<Book, BookDTO>(x => x.ID.Equals(ID), true);
                if (bookDto == null)
                {
                    return NotFound();
                }

                var authorDto = await _dbRead.GetAsync<Author, AuthorDTO>(true);
                SelectList selectList = new SelectList(authorDto, "ID", "Name", authorDto.Single(x => x.ID.Equals(bookDto.Author_ID)));
                var bookVieModel = new BookViewModel()
                {
                    Book = bookDto,
                    AuthorsList = selectList
                };
                return View(bookVieModel);
            }
        }
    }
}

VOD.Admin/Views/Book/BookList.cshtml
@model VOD.Admin.ViewModel.BookViewModel
@using X.PagedList.Mvc.Core;
@using X.PagedList.Mvc.Common;
@using X.PagedList;

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <h2>Index</h2>
    <div class="row">
        <div class="col-md-12">
            @Html.PagedListPager((IPagedList)this.Model.Books, page => Url.Action("BookList", "Book", new { id = page, authId = this.Model.Author_ID}), new PagedListRenderOptions
            { LiElementClasses = new string[] { "page-item" }, PageClasses = new string[] { "page-link" } })
        </div>
    </div>
    <p style="float:left">
        >
        <a asp-action="Create">Create New</a>
    </p>
    <div class="card" style="float:right;margin-left:200px;width: 20rem;">
        <div class="card-header">
            絞り込み検索
        </div>
        <div class="card-body">
            <form asp-action="BookList" asp-route-id="Book.Author_ID">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group dropdown">
                    <label asp-for="Book.Author.Name" class="control-label"></label>
                    <select asp-for="Book.Author_ID" asp-items="@Model.AuthorsList" class="form-control">
                        <option value="authId">選択してください</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </form>
            @*<label asp-for="Book.Author.Name" class="control-label"></label>
            <select asp-for="Book.Author_ID" asp-items="@Model.AuthorsList" class="form-control">
                <option value="">選択してください</option>
            </select>
            <input type="submit" asp-action="BookList" value="Search" class="btn btn-primary" asp-route-id="Book.Author_ID" />*@
        </div>
    </div>
    <p style="float:left;margin-left:200px">

        @*<div class="form-inline">
                <label asp-for="Book.Author.Name" class="control-label"></label>
                <select asp-for="Book.Author_ID" asp-items="@Model.AuthorsList" class="form-control">
                    <option value="">選択してください</option>
                </select>
                <a href="#" class="btn btn-primary">検索</a>
            </div>*@
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(vm => vm.Book.Title)</th>
                <th>@Html.DisplayNameFor(vm => vm.Book.Price)</th>
                <th>@Html.DisplayNameFor(vm => vm.Book.Publisher)</th>
                <th>@Html.DisplayNameFor(vm => vm.Book.Sample)</th>
                <th>@Html.DisplayNameFor(vm => vm.Book.ReleaseDate)</th>
                <th>@Html.DisplayNameFor(vm => vm.Book.Author.Name)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Books)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.Price)</td>
                    <td>@Html.DisplayFor(modelItem => item.Publisher)</td>
                    <td>@Html.DisplayFor(modelItem => item.Sample)</td>
                    <td>@Html.DisplayFor(modelItem => item.ReleaseDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.Author.Name)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

VOD.Admin/Views/Book/Create.cshtml

@model VOD.Admin.ViewModel.BookViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<h4>Book</h4>

<hr />

<!DOCTYPE html>

<div class="row">
    <div class="col-md4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Price" class="control-label"></label>
                <input asp-for="Book.Price" class="form-control" />
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publisher" class="control-label"></label>
                <input asp-for="Book.Publisher" class="form-control" />
                <span asp-validation-for="Book.Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="custom-checkbox">
                    <label asp-for="Book.Sample" class="control-label">
                        <input asp-for="Book.Sample" />@Html.DisplayNameFor(vm => vm.Book.Sample)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Book.ReleaseDate" class="control-label"></label>
                <input asp-for="Book.ReleaseDate" class="form-control" />
                <span asp-validation-for="Book.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group dropdown">
                <label asp-for="Book.Author.Name" class="control-label"></label>
                <select asp-for="Book.Author_ID" asp-items="@Model.AuthorsList" class="form-control">
                    <option value="">選択してください</option>
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

VOD.Admin/Views/Book/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model VOD.Admin.ViewModel.BookViewModel
@{
    ViewData["Title"] = "Delete";
}

<h2>確認画面</h2>
<h3>このデータを削除しますがよろしいですか？</h3>
<div>
    <h4>Book</h4>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Book.ID" />
        <input type="hidden" asp-for="Book.RowVersion" />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Title)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Price)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Publisher)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Publisher)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Sample)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Sample)
            </dd>
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.ReleaseDate)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.ReleaseDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Author.Name)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Author.Name)
            </dd>
        </dl>
        <div class=" btn-group-vertical">
            <div class="form-group">
                <input type="submit" value="Yes" class="btn btn-primary" />
                <input type="submit" asp-action="BookList" value="No" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

VOD.Admin/Views/Book/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model VOD.Admin.ViewModel.BookViewModel
@{
    ViewData["Title"] = "Delete";
}

<h2>詳細画面</h2>
<div>
    <h4>Book</h4>
    <hr />
    <form>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Title)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Price)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Publisher)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Publisher)
            </dd>

            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Sample)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Sample)
            </dd>
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.ReleaseDate)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.ReleaseDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(vm => vm.Book.Author.Name)
            </dt>
            <dd>
                @Html.DisplayFor(vm => vm.Book.Author.Name)
            </dd>
        </dl>
        <div class=" btn-group-vertical">
            <div class="form-group">
                <input type="submit" asp-action="BookList" value="Back" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

VOD.Admin/Views/Book/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model VOD.Admin.ViewModel.BookViewModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<h4>Book</h4>

<hr />

<div class="row">
    <div class="col-md4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Book.ID" />
            <input type="hidden" asp-for="Book.RowVersion" />
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Price" class="control-label"></label>
                <input asp-for="Book.Price" class="form-control" />
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Publisher" class="control-label"></label>
                <input asp-for="Book.Publisher" class="form-control" />
                <span asp-validation-for="Book.Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="custom-checkbox">
                    <label asp-for="Book.Sample" class="control-label">
                        <input asp-for="Book.Sample" />@Html.DisplayNameFor(vm => vm.Book.Sample)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Book.ReleaseDate" class="control-label"></label>
                <input asp-for="Book.ReleaseDate" class="form-control" />
                <span asp-validation-for="Book.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group dropdown">
                <label asp-for="Book.Author.Name" class="control-label"></label>
                <select asp-for="Book.Author_ID" asp-items="@Model.AuthorsList" class="form-control">
                    <option value="">選択してください</option>
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
